[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/work.html"
  to = "/work"
  status = 301
  force = true

[[redirects]]
  from = "/getstarted.html"
  to = "/getstarted"
  status = 301
  force = true

[[redirects]]
from = "/pricing.html"
to = "/pricing"
status = 301
force = true

[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/blog-website-cost-nigeria.html"
  to = "/blog-website-cost-nigeria"
  status = 301
  force = true

[[redirects]]
  from = "/blog-whatsapp-ai-bot-nigeria.html"
  to = "/blog-whatsapp-ai-bot-nigeria"
  status = 301
  force = true

[[redirects]]
  from = "/blog-5-stages-business-growth.html"
  to = "/blog-5-stages-business-growth"
  status = 301
  force = true

[[redirects]]
  from = "/blog-how-to-get-business-on-google-nigeria.html"
  to = "/blog-how-to-get-business-on-google-nigeria"
  status = 301
  force = true

[[redirects]]
  from = "/web-developer-ibadan.html"
  to = "/web-developer-ibadan"
  status = 301
  force = true

[[redirects]]
  from = "/work-orderflow-whatsapp-ai.html"
  to = "/work/orderflow-whatsapp-ai"
  status = 301
  force = true